lang:
  error:
    usage-hunger: "&4Usage: &f/hunger [<foodlevel> [<player>]]"
    usage-saturation: "&4Usage: &f/saturation [<saturationlevel> [<player>]]"
    usage-health: "&4Usage: &f/health [<healthlevel> [<player>]]"
    usage-xp: "&4Usage: &f/xp [<xp> [<player>]]"
    usage-level: "&4Usage: &f/level [<level>] [<player>]"
    no-permission: "&4Dir fehlt das Recht &f%perm%&4!"
    player-not-found: "&4Kein Spieler mit dem Namen &f%name%&4 online!"
    hunger-range: "&f%input% &4ist kleiner oder höher als das mögliche Hungerlevel (0 bis 20)!"
    saturation-range: "&f%input% &4ist kleiner oder höher als das mögliche Sättigungslevel (0 bis 20)!"
    health-range: "&f%input% &4ist kleiner oder höher als die möglichen Leben (0 bis 20)!"
    xp-range: "&f%input% &4ist kleiner oder höher als die mögliche Erfahrung (0 bis 2147483647)!"
    level-range: "&f%input% &4ist kleiner oder höher als die mögliche Erfahrung (0 bis 2147483647)!"
    wrong-hunger: "&f%input% &4ist keine ganze Zahl!"
    wrong-saturation: "&f%input% &4ist keine Zahl!"
    wrong-health: "&f%input% &4ist keine Zahl!"
    wrong-xp: "&f%input% &4ist keine Zahl!"
    wrong-level: "&f%input% &4ist keine Zahl!"
  success-hunger:
    own: "&7Hunger auf %value% gesetzt!"
    other: "&f%name%&7's Hunger auf %value% gesetzt!"
  success-saturation:
    own: "&7Sättigung auf %value% gesetzt!"
    other: "&f%name%&7's Sättigung auf %value% gesetzt!"
  success-health:
    own: "&7Leben auf %value% gesetzt!"
    other: "&f%name%&7's Leben auf %value% gesetzt!"
  success-xp:
    own: "&7Erfahrung auf %value% gesetzt!"
    other: "&f%name%&7's Erfahrung auf %value% gesetzt!"
  success-level:
    own: "&7Level auf %value% gesetzt!"
    other: "&f%name%&7's Level auf %value% gesetzt!"
  current-level:
    hunger: "&7Du hast momentan &f%value%&7 Hunger!"
    saturation: "&7Du hast momentan &f%value%&7 Sättigung!"
    health: "&7Du hast momentan &f%value%&7 Leben!"
    xp: "&7Du hast momentan &f%value%&7 Erfahrung!"
    level: "&7Du hast momentan &f%value%&7 Level!"
  current-level-other:
    hunger: "&f%player%&7 hat momentan &f%value%&7 Hunger!"
    saturation: "&f%player%&7 hat momentan &f%value%&7 Sättigung!"
    health: "&f%player%&7 hat momentan &f%value%&7 Leben!"
    xp: "&f%player%&7 hat momentan &f%value%&7 Erfahrung!"
    level:  "&f%player%&7 hat momentan &f%value%&7 Level!"