lang:
  prefix: "&8[&2Player&fValues&8]&f:"
  error:
    usage-hunger: "%prefix% &4Usage: &f/hunger [<foodlevel> [<player>]]"
    usage-saturation: "%prefix% &4Usage: &f/saturation [<saturationlevel> [<player>]]"
    usage-health: "%prefix% &4Usage: &f/health [<healthlevel> [<player>]]"
    usage-xp: "%prefix% &4Usage: &f/xp [<xp> [<player>]]"
    usage-level: "%prefix% &4Usage: &f/level [<level>] [<player>]"
    no-permission: "%prefix% &4Dir fehlt das Recht &f%perm%&4!"
    player-not-found: "%prefix% &4Kein Spieler mit dem Namen &f%name%&4 online!"
    hunger-range: "%prefix% &f%input% &4ist kleiner oder höher als das mögliche Hungerlevel (0 bis 20)!"
    saturation-range: "%prefix% &f%input% &4ist kleiner oder höher als das mögliche Sättigungslevel (0 bis 20)!"
    health-range: "%prefix% &f%input% &4ist kleiner oder höher als die möglichen Leben (0 bis 20)!"
    xp-range: "%prefix% &f%input% &4ist kleiner oder höher als die mögliche Erfahrung (0 bis 2147483647)!"
    level-range: "%prefix% &f%input% &4ist kleiner oder höher als die mögliche Erfahrung (0 bis 2147483647)!"
    wrong-hunger: "%prefix% &f%input% &4ist keine ganze Zahl!"
    wrong-saturation: "%prefix% &f%input% &4ist keine Zahl!"
    wrong-health: "%prefix% &f%input% &4ist keine Zahl!"
    wrong-xp: "%prefix% &f%input% &4ist keine Zahl!"
    wrong-level: "%prefix% &f%input% &4ist keine Zahl!"
  success-hunger:
    own: "%prefix% &7Hunger auf %value% gesetzt!"
    other: "%prefix% &f%name%&7's Hunger auf %value% gesetzt!"
  success-saturation:
    own: "%prefix% &7Sättigung auf %value% gesetzt!"
    other: "%prefix% &f%name%&7's Sättigung auf %value% gesetzt!"
  success-health:
    own: "%prefix% &7Leben auf %value% gesetzt!"
    other: "%prefix% &f%name%&7's Leben auf %value% gesetzt!"
  success-xp:
    own: "%prefix% &7Erfahrung auf %value% gesetzt!"
    other: "%prefix% &f%name%&7's Erfahrung auf %value% gesetzt!"
  success-level:
    own: "%prefix% &7Level auf %value% gesetzt!"
    other: "%prefix% &f%name%&7's Level auf %value% gesetzt!"
  current-level:
    hunger: "%prefix% &7Du hast momentan &f%value%&7 Hunger!"
    saturation: "%prefix% &7Du hast momentan &f%value%&7 Sättigung!"
    health: "%prefix% &7Du hast momentan &f%value%&7 Leben!"
    xp: "%prefix% &7Du hast momentan &f%value%&7 Erfahrung!"
    level: "%prefix% &7Du hast momentan &f%value%&7 Level!"
  current-level-other:
    hunger: "%prefix% &f%player%&7 hat momentan &f%value%&7 Hunger!"
    saturation: "%prefix% &f%player%&7 hat momentan &f%value%&7 Sättigung!"
    health: "%prefix% &f%player%&7 hat momentan &f%value%&7 Leben!"
    xp: "%prefix% &f%player%&7 hat momentan &f%value%&7 Erfahrung!"
    level: "%prefix% &f%player%&7 hat momentan &f%value%&7 Level!"